Ac product
nss-copper-dragonflies/BangazonAPI pull request #16
Opened 2019-04-02 19:38 UTC by allisonkatecollins

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing Instructions

Please describe the tests required to verify your changes. Provide instructions so PR Tester can check functionality. Please also list any relevant details for your tests

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added test instructions that prove my fix is effective or that my feature works

2019-04-02 19:59 UTC, bramosja approved these changes
Postman CRUD works and all tests work!

2019-04-02 20:16 UTC, JordanRosas approved these changes
looks guuuuuuuuuuuuuuud

2019-04-02 21:15 UTC, askingalot requested changes

2019-04-02 21:15 UTC, askingalot commented on BangazonAPI/Controllers/ProductController.cs
> +﻿//author: Allison Collins. This method has the HTTP methods to GET all, GET single, POST, PUT, and DELETE data.
Please add comments above each method to say what it does.

2019-04-03 14:53 UTC, askingalot approved these changes

2019-04-03 14:54 UTC, merged